### ISSUE TITLE
Pipeline optimization

### ISSUE THREAD

**Issue by louis030195** [louis030195/vision-client#10]
Input pubsub triggered too many times
Upload 200 frames =>

![Screenshot from 2019-08-23 18-02-17](https://user-images.githubusercontent.com/25003283/63606378-3ab01b00-c5d0-11e9-945a-7f15b7e8c8f4.png)

Obviously the firsts triggers push everything in the Pub/Sub queue, then the function is called ~200 times for nothing, would it be better to switch to a http / pubsub trigger from back API calling just once after multiple files have been uploaded ?

**Comment by louis030195** [comment]
same thing for predictor 

![Screenshot from 2019-08-23 18-06-49](https://user-images.githubusercontent.com/25003283/63606629-cd50ba00-c5d0-11e9-82d4-3f1eac616d13.png)

anyway predictor do a sync pull of Pub/Sub so i think it would be better that input push all the frames to process in the queue and call predictor once with http

**Comment by rom1504** [comment]
You can do http trigger from back + cron every 30min in case something
didn't trigger

**Comment by louis030195** [comment]
HTTP trigger from back once files uploaded + cron every x minutes done

Optimally the cron would change it's frequency according to the traffic on the site or something like that ^^

Now maybe could do http trigger input_pubsub => predictor to reduce useless calls again
