### ISSUE TITLE
AI Platform - batch predictions quota

### ISSUE THREAD

**Issue by louis030195** [louis030195/vision-client#7]
>File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 383, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 214, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 100, in batch_prediction print('Response', batch_predict(PROJECT_ID, body)) File "/user_code/main.py", line 68, in batch_predict response = request.execute() File "/env/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper return wrapped(*args, **kwargs) File "/env/local/lib/python3.7/site-packages/googleapiclient/http.py", line 855, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError: <HttpError 429 when requesting https://ml.googleapis.com/v1/projects/wildlife-247309/jobs?alt=json returned "Quota failure for project wildlife-247309. The project is already using 80 CPU cores for batch prediction. This job additionally requires 10 CPU cores, which in total would exceed the allowed maximum of 72 cores. To read more about Cloud ML Engine quota, see https://cloud.google.com/ml-engine/quotas.">

**Comment by louis030195** [comment]
for 7 images (as a tfrecord)

**Comment by rom1504** [comment]
You need to limit the number of concurrent batch prediction (probably using
the queue)

**Comment by louis030195** [comment]
I don't think AI Platform does concurrent batch predictions for only 1 tfrecord ?

Anyway solved for now by putting a smaller model

[model list](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models)
faster_rcnn_resnet101_coco (115mb) -> ssd_mobilenet_v1_coco (28mb)

When creating a model / version we can either choose 1 CPU or 4, it could be tried also btw

**Comment by louis030195** [comment]
![Screenshot from 2019-08-09 10-13-20](https://user-images.githubusercontent.com/25003283/62764506-596dc800-ba8e-11e9-8337-89678f7a63db.png)

Ok maybe it does concurrent batch prediction

**Comment by louis030195** [comment]
@rom1504 btw there was multiple concurrent job because the tfrecord caller function had multiple concurrent instances (so creating multiple tfrecord so calling multiple batch job ...) https://github.com/louis030195/vision-client/commit/fa5d8dbf60e899112a46b18b14ae8d93ee7f1089#diff-04c6e90faac2675aa89e2176d2eec7d8R85
